### ISSUE TITLE
feat: add commitizen to pre-commits

### ISSUE THREAD

**Issue by second-ed** [spencerduberry/football-pipeline#15]
add to the project dependencies
```shell
uv add --dev commitizen
```

add to the list of repos in pre-commit:
```yaml
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v1.17.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
```
