### ISSUE TITLE
feat: add hooks to pre-commits

### ISSUE THREAD

**Issue by second-ed** [spencerduberry/football-pipeline#16]
add to the list of repos in pre-commit:
```yaml
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml
```
