### ISSUE TITLE
feat: read_yaml to io.py

### ISSUE THREAD

**Issue by second-ed** [spencerduberry/football-pipeline#5]
Function that takes a path to a yaml file and returns the data as a dictionary 
should catch errors if theres an exception and return an empty dictionary

Will need to add the `pyyaml` dependency to the package with this command from the root of the repo after running `uv venv ; uv sync`
```shell
uv add pyyaml
```

## function signature
```python
def read_yaml(path: str) -> dict:
```

Tests should:
-  read a test yaml files (store in `tests/mock_data/mock_yamls/`) and assert the expected dict is returned
- assert that the error is caught when given something invalid or unexpected

test cases:
```yaml
# tests/mock_data/mock_yamls/valid.yaml
league:
  backseries: False
  players:
    - some player
    - some other player
```

```yaml
# tests/mock_data/mock_yamls/invalid.yaml
league
  backseries: False
  players:
    - some player
    - some other player
```
